### ISSUE TITLE
Problemy z notebookami

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/emosie#1]

**Comment by pbarkowski** [comment]
Przybywam zarówno z problemami, jak i ich rozwiązaniami :D
***
1. literówka w tekście nad 13 komórką z kodem:

> _Chcemy aby funkcją kosztu była '**binary_corssentropy**' (będziemy jej zawsze używać dla problemów klasyfikacyjnych)._

jest binary_corssentropy a powinno być binary_crossentropy :)
***
2. po pierwszym treningu pies vs kot w momencie gdy sprawdzam sobie pojedyncze pliki z 25 pierwszych zdjęć testowych, to wyskakuje mi coś jak poniżej w obu komórkach:

![image](https://user-images.githubusercontent.com/23636909/39955887-0e009144-55d7-11e8-879d-318b1da88d68.png)

Żeby cokolwiek nam pokazało, trzeba kod
`plt.imshow(test_sample[check_idx])`
zmienić na:
`plt.imshow(test_sample[check_idx]/255)`

I wszystko działa:
![image](https://user-images.githubusercontent.com/23636909/39955973-1888f8e4-55d8-11e8-94cb-94b3f05bf329.png)
***
3. dałeś tutaj w komórce kod do uzupełnienia jako ćwiczenie oraz rozwiązanie zaraz pod nim :)

![image](https://user-images.githubusercontent.com/23636909/39956014-b0ecc9f8-55d8-11e8-813f-42b40e35434b.png)
***
4. W markdown nie działa gif z tagiem `<img>`:
`<img src=https://ahmedbesbes.com/images/GIF.gif>`
ale to zadziała:
`![](https://ahmedbesbes.com/images/GIF.gif)`

**Comment by pbarkowski** [comment]
I jeszcze 3 - dałeś tutaj w komórce kod do uzupełnienia jako ćwiczenie oraz rozwiązanie zaraz pod nim :)

![image](https://user-images.githubusercontent.com/23636909/39956014-b0ecc9f8-55d8-11e8-813f-42b40e35434b.png)

**Comment by mmagnuski** [comment]
@pbarkowski Dzięki za uwagi!
1. Na zajęciach sporo osób miało z tym problem, z których część zdała sobie sprawę, że to literówka. Ja też. :)
2. Wydaje mi się że to wynika z wersji matplotliba, bo u mnie ten fragment kodu działał. Ale dobrze, że mówisz - zmienię to. Zresztą i tak lepiej obrazki skalować/normalizować jeszcze przed treningiem, także tak zrobię w notebook'u na najbliższe zajęcia.
3. Ach, tak, czasami zapomnę usunąć fragmentów, które powinniście później uzupełnić. :)
4. W notebook'u powinien działać, mi w każdym razie działa. Którą masz wersję jupyter notebook'a?

**Comment by Malgosia20** [comment]
na zajeciach komputer dwa razy zacial sie przy pierwszym treningu i mialam poprobowac w domu , ale mam problem z kerasem, jakies rady? instalowalam poleceniem conda install keras
![image](https://user-images.githubusercontent.com/23696074/40410432-1aba4c64-5e6e-11e8-858f-9964e0666ef6.png)

**Comment by pbarkowski** [comment]
@mmagnuski 
mam straszny nawyk zaczynania pracy z komendą `conda update --all` :) dlatego wersję notebooka mam chyba aktualną:
![image](https://user-images.githubusercontent.com/23636909/40413882-3d9dd31e-5e77-11e8-9e6e-4ef73572789b.png)

@Malgosia20 
- pokaż dalej ten komunikat, co jest całkiem na dole?
- korzystasz z anaconda prompt czy z wiersza poleceń? u mnie w wierszu poleceń nie działają komendy z condy

**Comment by NataliaTabi** [comment]
Mam problem z ostatnią częścią z zajęć 6. Cały czas mi wychodzi taki błąd bez względu na to jakie mu podam dane:
![problem z zad6](https://user-images.githubusercontent.com/23664372/40426867-6f2bbdae-5e9c-11e8-9d29-03ed770a618e.png)

**Comment by mmagnuski** [comment]
@pbarkowski 
Hm, ok, to zresztą całkiem dobry nawyk :) (którego ja akurat nie mam). Tak czy siak - zgodnie ze specyfikacją HTML parametry takie jak te linki mogą nie być otoczone cudzysłowem, kiedy nie zawierają pewnych znaków specjalnych (a nie zawierają, bo to linki). Ale postaram się na przyszłość wpisywać inaczej aby nikt nie miał problemu z wyświetlaniem.

@Malgosia20 
To jest błąd w condzie (tak jak sugeruje treść błędu prosząca aby zgłosić błąd na githubie). Zanim jednak zgłosimy Twój błąd spróbuj najpierw zupdate'ować condę:
```
conda update conda
```
i dopiero wtedy instaluj Keras.

@NataliaTabi 
To faktycznie nie jest zbyt czytelny błąd, ale może masz coś nie tak w zmiennej `images`. Co Ci wyskakuje gdy piszesz:
```
print(type(images))
print(images.dtype)
print(images.shape)
print(images)
```
?

**Comment by Malgosia20** [comment]
![image](https://user-images.githubusercontent.com/23696074/40515905-ff78c8e4-5fae-11e8-886c-4f602392b758.png)


cos mi sie zdaje że to z wiersza polecen nie pojdzie

**Comment by NataliaTabi** [comment]
![image](https://user-images.githubusercontent.com/23664372/40555239-b390129e-6048-11e8-9e3a-071e0a257d8b.png)
tak wychodzi

**Comment by pbarkowski** [comment]
@Malgosia20 
musisz użyć anaconda prompt, a nie windowsowego wiersza poleceń.

żeby wszystko uaktualnić na max, musisz wpisać po kolei, w każdym akceptując instalację wszystkiego:
`conda update -n base conda`
`conda install keras`
`conda update --all` (tutaj, jeśli od dawna nie aktualizowałaś, pójdzie raczej długo)

**Comment by mmagnuski** [comment]
@NataliaTabi
Sprawdziłem - w notebook'u jest błąd po prostu. Skasowałem przez przypadek komórkę potrzebną do jego poprawnego działania. Zrób tak:
```python
images = X[[1543, 5623]]
```
w ten sposób wyciągasz z `X` tylko elementy `1543` oraz `5623` (o których jest mowa w opisie powyżej szwankującej komórki) i zapiszesz w zmiennej `images`.

**Comment by mmagnuski** [comment]
@Malgosia20 @pbarkowski 
Po błędzie widać, że `conda` się odpala z terminala, ale jest błąd. Wątpię aby z Anaconda Prompt poszło bez błędu. Dobrze byłoby gdybyś skopiowała cały tekst błędu - zgłosimy problem na githubie condy.
Możliwe zresztą, że już ktoś ten błąd zgłosił i jest jakieś rozwiązanie, ale trudno to ocenić bez całej informacji o błędzie.
Jak już skopiujesz błąd i wkleisz tutaj, możesz również spróbować zreinstalować anacondę (odinstalować normalnie poprzez dodaj/usuń programy a następnie zainstalować, z instalatora z najnowszej wersji z netu).

**Comment by pbarkowski** [comment]
Ok, sorry za wprowadzenie w błąd - u mnie w wierszu poleceń nie działają komendy condy - i dlatego myślałem, że wszędzie tak może być :)

**Comment by mmagnuski** [comment]
@pbarkowski
Widocznie nie masz folderu ze skryptami anacondy dodanego do zmiennej środowiskowej PATH - ale jak Ci to nie przeszkadza, to nie ma potrzeby zmieniać.

**Comment by pbarkowski** [comment]
Ponownie wracam z komunikatem `Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).` podczas próby pokazania obrazu - tym razem w rozdziale **Czego nauczyła się nasza sieć**. Poniżej odpaliłem też zawartość zmiennej `img`.

![image](https://user-images.githubusercontent.com/23636909/40584476-9ae49cce-61a1-11e8-8e60-c85232ad0d27.png)


Poprzednia sztuczka z podzieleniem przez 255 tym razem nie działa:

![image](https://user-images.githubusercontent.com/23636909/40584488-ccbef88e-61a1-11e8-93a7-64c4e1ed466e.png)

Jakieś sugestie? :)

**Comment by mmagnuski** [comment]
Możesz spróbować z `img.astype('int')` ale i tak myślę, że to dziwne że Ci nie działa. Którą wersję pythona numpy'a i matplotliba masz? (jak updateujesz wszystko to ze względu na ze inne pakiety mogą wymagać wczesniejszych wersji wcale nie musisz mieć najnowszej). Ten argument `input_range` powinien zapewniać wartości w odpowiednim zakresie, ale mam wrażenie że wczesniejszy matplotlib mógł patrzeć na zakres 0 - 255 tylko gdy typ zmiennej jest int. Teraz wydaje mi się że 0-255 działa nawet dla danych typu float. Ale skoro dzielenie przez 255 nie działa to pokaż ile wynosi max i min tej macierzy img?

**Comment by pbarkowski** [comment]
Aktualne wersje bibliotek:
![image](https://user-images.githubusercontent.com/23636909/40642603-d9e9d5ce-631d-11e8-9d63-47079dbb1eca.png)

Próba z `img.astype('int')` kończy się takim samym stanem jak `img/255`:
![image](https://user-images.githubusercontent.com/23636909/40642753-509451a4-631e-11e8-92b7-e5b736b1d09f.png)

min i max zmiennej img:
![image](https://user-images.githubusercontent.com/23636909/40642804-703526fa-631e-11e8-9d8e-e3d48aef7796.png)

Jeśli nie uda się nam nic wykombinować, po prostu na cele projektu przeinstaluję wszystko bez aktualizowania :)

**Comment by mmagnuski** [comment]
@pbarkowski 
Wydaje mi się w związku z tym, że to raczej kwestia wag zmiennych `tv_weight` oraz `lp_norm_weight`, które niestety często trzeba ręcznie dostosowywać aż osiągnie się sensowny wynik (możesz spróbować obniżyć `tv_weight`, które określa wkład kary za zbytnią zmienność sąsiadujących pikseli). Czy dla wszystkich filtrów wychodzi Ci taki "płaski" obrazek? Jeżeli nie - może ten filtr akurat lubi jednorodnie zielone fragmenty?
Jeżeli dodasz do funkcji argument `verbose=1`, to dla każdej iteracji dopasowywania pikseli będziesz widział jaki jest koszt (`Loss`), to może nam pomóc namierzyć problem. Ale nie warto nad tym siedzieć zbyt długo - to jest jedna z wielu metod, której celem jest lepsze zrozumienie na co czułe są konkretne filtry.

**Comment by Malgosia20** [comment]
Hej, tutaj wklejam cały bład ktory pojawia sie po poleceniu conda update conda
Przez to nie moge pojsc dalej z kerasem. Spróbuje zaintalowac to wszystko od nowa
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\Małgosia>conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 573, in con
da_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Public\lib\site-packages\conda\cli\main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "C:\Users\Public\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Public\lib\site-packages\conda\cli\main_list.py", line 20, in <
module>
    from ..egg_info import get_egg_info
  File "C:\Users\Public\lib\site-packages\conda\egg_info.py", line 15, in <modul
e>
    from .misc import rel_path
  File "C:\Users\Public\lib\site-packages\conda\misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "C:\Users\Public\lib\site-packages\conda\core\index.py", line 8, in <modu
le>
    from .package_cache import PackageCache
  File "C:\Users\Public\lib\site-packages\conda\core\package_cache.py", line 10,
 in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Public\lib\site-packages\conda\core\path_actions.py", line 31,
in <module>
    from ..gateways.download import download
  File "C:\Users\Public\lib\site-packages\conda\gateways\download.py", line 16,
in <module>
    from ..connection import CondaSession
  File "C:\Users\Public\lib\site-packages\conda\connection.py", line 29, in <mod
ule>
    from .gateways.anaconda_client import read_binstar_tokens
ModuleNotFoundError: No module named 'conda.gateways.anaconda_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Public\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Public\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 589, in con
da_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 543, in pri
nt_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 513, in get
_info
    args.func(args, p)
  File "C:\Users\Public\lib\site-packages\conda\cli\main_info.py", line 148, in
execute
    from conda.api import get_index
  File "C:\Users\Public\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\Public\lib\site-packages\conda\core\index.py", line 8, in <modu
le>
    from .package_cache import PackageCache
  File "C:\Users\Public\lib\site-packages\conda\core\package_cache.py", line 10,
 in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Public\lib\site-packages\conda\core\path_actions.py", line 31,
in <module>
    from ..gateways.download import download
  File "C:\Users\Public\lib\site-packages\conda\gateways\download.py", line 16,
in <module>
    from ..connection import CondaSession
  File "C:\Users\Public\lib\site-packages\conda\connection.py", line 29, in <mod
ule>
    from .gateways.anaconda_client import read_binstar_tokens
ModuleNotFoundError: No module named 'conda.gateways.anaconda_client'

C:\Users\Małgosia>

**Comment by Malgosia20** [comment]
ale przy ponownej instalacji i wpisaniu conda install seaborn
tez pojawia sie dziwny blad, wiec juz sama nie wiem o co chodzi

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\Małgosia>python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v
.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

C:\Users\Małgosia>conda install seaborn
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 573, in con
da_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Public\lib\site-packages\conda\cli\main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "C:\Users\Public\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Public\lib\site-packages\conda\cli\main_list.py", line 20, in <
module>
    from ..egg_info import get_egg_info
  File "C:\Users\Public\lib\site-packages\conda\egg_info.py", line 15, in <modul
e>
    from .misc import rel_path
  File "C:\Users\Public\lib\site-packages\conda\misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "C:\Users\Public\lib\site-packages\conda\core\index.py", line 8, in <modu
le>
    from .package_cache import PackageCache
  File "C:\Users\Public\lib\site-packages\conda\core\package_cache.py", line 10,
 in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Public\lib\site-packages\conda\core\path_actions.py", line 31,
in <module>
    from ..gateways.download import download
  File "C:\Users\Public\lib\site-packages\conda\gateways\download.py", line 16,
in <module>
    from ..connection import CondaSession
  File "C:\Users\Public\lib\site-packages\conda\connection.py", line 29, in <mod
ule>
    from .gateways.anaconda_client import read_binstar_tokens
ModuleNotFoundError: No module named 'conda.gateways.anaconda_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Public\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Public\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 589, in con
da_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 543, in pri
nt_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\Public\lib\site-packages\conda\exceptions.py", line 513, in get
_info
    args.func(args, p)
  File "C:\Users\Public\lib\site-packages\conda\cli\main_info.py", line 148, in
execute
    from conda.api import get_index
  File "C:\Users\Public\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\Public\lib\site-packages\conda\core\index.py", line 8, in <modu
le>
    from .package_cache import PackageCache
  File "C:\Users\Public\lib\site-packages\conda\core\package_cache.py", line 10,
 in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Public\lib\site-packages\conda\core\path_actions.py", line 31,
in <module>
    from ..gateways.download import download
  File "C:\Users\Public\lib\site-packages\conda\gateways\download.py", line 16,
in <module>
    from ..connection import CondaSession
  File "C:\Users\Public\lib\site-packages\conda\connection.py", line 29, in <mod
ule>
    from .gateways.anaconda_client import read_binstar_tokens
ModuleNotFoundError: No module named 'conda.gateways.anaconda_client'

C:\Users\Małgosia>

**Comment by mmagnuski** [comment]
@Malgosia20 
Przy pierwszym i drugim podejściu dostajesz ten sam błąd ponieważ to jest jakiś błąd condy. Niestety nie rozwiążemy tego raczej inaczej niż poprzez reinstalację. Dodaj/usuń programy -> usuń anacondę i zainstaluj ponownie (najnowszą wersję).

**Comment by Malgosia20** [comment]
ale to własnie robie w drugim miejscu, usunełam tamtą conde i instalowałam
nową

W dniu 10 czerwca 2018 00:10 użytkownik Mikolaj Magnuski <
notifications@github.com> napisał:

**Comment by Malgosia20** [comment]
instaluje teraz na innym laptopie i takiego czegos jeszcze nie mialam, co tym razem sie dzieje ze pakiet mne nie chce wejsc ?
![image](https://user-images.githubusercontent.com/23696074/41202066-2c3a8cc4-6cc4-11e8-8177-600dfa50221a.png)

**Comment by Malgosia20** [comment]
![image](https://user-images.githubusercontent.com/23696074/41202080-6d87a46e-6cc4-11e8-85a3-a316faca1694.png)

**Comment by mmagnuski** [comment]
@Malgosia20
Nie potrzebujesz mne, ani cmder.

**Comment by Malgosia20** [comment]
a mypy? probowalam zainstalowac  to wszystko co jest podane w podstawowej instalacji,

**Comment by mmagnuski** [comment]
`mypy` też nie powinien być potrzebny. Instalacja dotyczy zajęć z poprzedniego semestru, prawda? Dla tego semestru istotne są tylko: Anaconda i keras (opcjonalnie do niektórych notebooków potrzebne są inne biblioteki jak np. `ipyvolume`, które sprawiło nam dziś tyle niespodziewanych kłopotów, że wycofałem się do głębin podświadomości ze smutku).
